<?php
return [
    "KIR" => 1,
    "TOD" => 2,
    "EDO" => 3,
    "HMD" => 4,
    "TMG" => 5,
    "HNM" => 6,
    "GAM" => 7,
    "TOK" => 8,
    "TSU" => 9,
    "MKG" => 10,
    "BIW" => 11,
    "SUM" => 12,
    "AMG" => 13,
    "NAR" => 14,
    "MRK" => 15,
    "KJM" => 16,
    "MIY" => 17,
    "TKY" => 18,
    "SHN" => 19,
    "WKM" => 20,
    "ASH" => 21,
    "FUK" => 22,
    "KAR" => 23,
    "OMR" => 24,
];