<?php
return [
    "KRY" => 1,
    "TDA" => 2,
    "EDG" => 3,
    "HWJ" => 4,
    "TMG" => 5,
    "HMN" => 6,
    "GMG" => 7,
    "TKN" => 8,
    "TSU" => 9,
    "MKN" => 10,
    "BWK" => 11,
    "SME" => 12,
    "AMG" => 13,
    "NRT" => 14,
    "MRG" => 15,
    "KJM" => 16,
    "MYJ" => 17,
    "TKY" => 18,
    "SMS" => 19,
    "WKM" => 20,
    "ASY" => 21,
    "FKO" => 22,
    "KRT" => 23,
    "OMR" => 24,
];