<?php
return [
    1  => "KIR",
    2  => "TOD",
    3  => "EDO",
    4  => "HMD",
    5  => "TMG",
    6  => "HNM",
    7  => "GAM",
    8  => "TOK",
    9  => "TSU",
    10 => "MKG",
    11 => "BIW",
    12 => "SUM",
    13 => "AMG",
    14 => "NAR",
    15 => "MRK",
    16 => "KJM",
    17 => "MIY",
    18 => "TKY",
    19 => "SHN",
    20 => "WKM",
    21 => "ASH",
    22 => "FUK",
    23 => "KAR",
    24 => "OMR",
];