<?php
declare(strict_types=1);
require_once __DIR__ . '/../common/db_connect.php';
$from=$argv[1]??'2026-06-15';$to=$argv[2]??'2026-07-14';if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)||$from>$to){fwrite(STDERR,"日付指定エラー\n");exit(1);} 
$f=json_decode((string)file_get_contents(__DIR__.'/../theories/new_sam/features.json'),true);$pdo=getPDO();
const I=['-0.6未満','-0.6--0.4','-0.4--0.2','-0.2-0.0','0.0-0.2','0.2-0.4','0.4-0.6','0.6以上'];const Z=['GOOD','NEUTRAL','BAD'];
function iv(float $x):string{return $x<-.6?I[0]:($x<-.4?I[1]:($x<-.2?I[2]:($x<0?I[3]:($x<.2?I[4]:($x<.4?I[5]:($x<.6?I[6]:I[7]))))));}function zn(float $x):string{return $x<-.2?'GOOD':($x<.2?'NEUTRAL':'BAD');}
function b():array{return ['n'=>0,'f'=>0,'t3'=>0,'sum'=>0.0,'mix'=>[]];}function add(array &$b,string $v,int $c,float $r):void{$b['n']++;if($r===1.0)$b['f']++;if($r<=3)$b['t3']++;$b['sum']+=$r;$b['mix'][$v][$c]=($b['mix'][$v][$c]??0)+1;}function ba(array &$b,float $r):void{$b['n']=($b['n']??0)+1;if($r===1.0)$b['f']=($b['f']??0)+1;if($r<=3)$b['t3']=($b['t3']??0)+1;}
function er(array $b,array $base,string $m):float{if(!$b['n'])return 0;$s=0;foreach($b['mix'] as $v=>$cs)foreach($cs as $c=>$n){$x=$base[$v][$c]??null;if($x&&$x['n'])$s+=$n*(($x[$m]??0)/$x['n']*100);}return $s/$b['n'];}function sm(array $b,array $base):array{$n=$b['n'];$fr=$n?$b['f']/$n*100:0;$tr=$n?$b['t3']/$n*100:0;return ['n'=>$n,'f'=>$fr,'t'=>$tr,'avg'=>$n?$b['sum']/$n:0,'lf'=>$fr-er($b,$base,'f'),'lt'=>$tr-er($b,$base,'t3')];}
function judge(array $z,array $base):string{$g=sm($z['GOOD'],$base);$n=sm($z['NEUTRAL'],$base);$b=sm($z['BAD'],$base);if(min($g['n'],$n['n'],$b['n'])<50)return'SMALL';$fo=$g['lf']>$n['lf']&&$n['lf']>$b['lf'];$to=$g['lt']>$n['lt']&&$n['lt']>$b['lt'];$sg=$g['lt']>0&&$b['lt']<0;return$fo&&$to&&$sg?'OK':(($fo||$to)&&$sg?'MIXED':'NG');}
$rq=$pdo->prepare("SELECT DISTINCT race_code FROM boat_race.race_entry WHERE race_date BETWEEN :f AND :t ORDER BY race_code");$rq->execute([':f'=>$from,':t'=>$to]);$races=$rq->fetchAll(PDO::FETCH_COLUMN);$eq=$pdo->prepare("SELECT entry_course,exhibition_time,lap_time,around_time,straight_time FROM boat_race.exhibition_live WHERE race_code=:r ORDER BY entry_course");$resq=$pdo->prepare("SELECT el.entry_course,rrd.rank FROM boat_race.exhibition_live el JOIN boat_race.race_entry re ON re.race_code=el.race_code AND re.player_id=el.player_id LEFT JOIN boat_race.race_result_detail rrd ON rrd.race_code=re.race_code AND rrd.player_id=re.player_id WHERE el.race_code=:r ORDER BY el.entry_course");
$ib=[];$zb=[];foreach(I as $x)$ib[$x]=b();foreach(Z as $x)$zb[$x]=b();$vz=[];$base=[];$cnt=[];$skip=['not_6_exhibition'=>0,'missing_feature'=>0,'missing_result'=>0];$p=0;
foreach($races as $rc){$v=substr((string)$rc,8,3);$cols=$f[$v]??null;if(!is_array($cols)||count($cols)!==3)continue;$eq->execute([':r'=>$rc]);$erows=$eq->fetchAll(PDO::FETCH_ASSOC);if(count($erows)!==6){$skip['not_6_exhibition']++;continue;}$raw=[];$bad=false;foreach($erows as $x){$c=(int)$x['entry_course'];$s=0;foreach($cols as $k){if($x[$k]===null||$x[$k]===''||!is_numeric($x[$k])){$bad=true;break 2;}$s+=(float)$x[$k];}$raw[$c]=$s;}if($bad||count($raw)!==6){$skip['missing_feature']++;continue;}$resq->execute([':r'=>$rc]);$rr=$resq->fetchAll(PDO::FETCH_ASSOC);if(count($rr)!==6){$skip['missing_result']++;continue;}$rank=[];$has=false;$bad=false;foreach($rr as $x){$c=(int)$x['entry_course'];$r=$x['rank'];if($r===null||$r==='')$rank[$c]=5.5;elseif(in_array((string)$r,['1','2','3','4','5','6'],true)){$rank[$c]=(float)$r;$has=true;}else{$bad=true;break;}}if($bad||!$has||count($rank)!==6){$skip['missing_result']++;continue;}if(!isset($vz[$v])){foreach(Z as $x)$vz[$v][$x]=b();$cnt[$v]=0;}$cnt[$v]++;$p++;$avg=array_sum($raw)/6;foreach($rank as $c=>$r){if(!isset($base[$v][$c]))$base[$v][$c]=['n'=>0,'f'=>0,'t3'=>0];ba($base[$v][$c],$r);$d=$raw[$c]-$avg;$i=iv($d);$z=zn($d);add($ib[$i],$v,$c,$r);add($zb[$z],$v,$c,$r);add($vz[$v][$z],$v,$c,$r);}}
ksort($vz);echo"========================================\nSUM理論 健康診断 v2（player_id結果対応）\n========================================\n期間       : $from ～ $to\n対象レース : ".count($races)."\n処理レース : $p\n評価艇数   : ".($p*6)."\n結果対応   : exhibition→race_entry→result を player_id 結合\n着外処理   : rank NULL/空 = 5.5\n";echo"\n【除外・スキップ参考】\n";foreach($skip as $k=>$n)printf("%-24s : %d\n",$k,$n);echo"\n【SUM差分 8区間】\n";foreach(I as $x){$s=sm($ib[$x],$base);printf("%-12s N=%5d 1着=%6.2f%% 3連=%6.2f%% 平均=%.3f | lift 1着=%+6.2f 3連=%+6.2f\n",$x,$s['n'],$s['f'],$s['t'],$s['avg'],$s['lf'],$s['lt']);}echo"\n【3ゾーン】\n";foreach(Z as $x){$s=sm($zb[$x],$base);printf("%-7s N=%5d 1着=%6.2f%% 3連=%6.2f%% | lift 1着=%+6.2f 3連=%+6.2f\n",$x,$s['n'],$s['f'],$s['t'],$s['lf'],$s['lt']);}echo"\n【場別】\n";foreach($vz as $v=>$z){echo"\n[$v] ".implode('+',$f[$v])." races={$cnt[$v]} judge=".judge($z,$base)."\n";foreach(Z as $x){$s=sm($z[$x],$base);printf("  %-7s N=%4d lift 1着=%+6.2f 3連=%+6.2f\n",$x,$s['n'],$s['lf'],$s['lt']);}}echo"\n========================================\n見るポイント\n========================================\n・missing_resultが前版より大幅に減るか\n・GOODがプラス、BADがマイナスを2期間再現するか\n・場別表示が広く復活するか\n========================================\n";
